"""Add image column to birds

Revision ID: 7b212d9ba4a1
Revises: 1be0580acb98
Create Date: 2023-12-11 21:28:22.145582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b212d9ba4a1'
down_revision = '1be0580acb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('birds', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('birds', 'species',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('birds', 'species',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('birds', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
